# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 14:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lab_page.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=lab_page.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('content', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=200)),
                ('mata_description', models.TextField(blank=True, max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Travels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_region', models.CharField(max_length=230, null=True, unique=True)),
                ('region', models.CharField(max_length=230, null=True, unique=True)),
                ('district', models.CharField(max_length=230, null=True, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Sklad',
        ),
        migrations.AddField(
            model_name='post',
            name='travels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_page.Travels'),
        ),
    ]
