# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 15:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lab_page', '0002_auto_20170225_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='travels',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2017, 2, 25, 15, 10, 41, 405665, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
