# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_page', '0004_auto_20170225_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travels',
            name='district',
            field=models.CharField(max_length=230, null=True),
        ),
    ]
