# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_page', '0005_auto_20170225_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travels',
            name='region',
            field=models.CharField(max_length=230, null=True),
        ),
    ]
