# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 10:08
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lab_page', '0006_auto_20170225_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content2',
            field=ckeditor.fields.RichTextField(default=datetime.datetime(2017, 3, 6, 10, 8, 42, 863249, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
