# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 10:13
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lab_page', '0007_post_content2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content2',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(default=datetime.datetime(2017, 3, 6, 10, 13, 3, 634945, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
