# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import lab_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_page', '0009_auto_20170307_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', help_text='150x150px', null=True, upload_to=lab_page.models.upload_location, verbose_name='Фото локації', width_field='width_field'),
        ),
    ]
