# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_page', '0010_auto_20170307_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='mata_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='meta_keywords',
        ),
    ]
